### ISSUE TITLE
Position incorrect when on fixed elements 

### ISSUE THREAD

**Issue by MattShrider** [hakib/MassAutocomplete#13]
JSbin with issuee:
http://jsbin.com/xirukapuho/1/edit?html,css,js,output

When the dropdown is on a fixed element, floating somewhere below the top of the page, the dropdown position is calculated incorrectly.  I think this is due to the fact that the position is calculated relative to the document, but the absolute style is relative to the parent.

This could solved by finding the directive element's offset from the top of the page (and left) and subtracting from the position value.

**Comment by elifio** [comment]
I'm Using ngDialog a ngmodule to open modals windows
 and displays also in the wrong position.

It is possible to solve the problem by changing the position in the script

You can see in the plunker

http://plnkr.co/edit/4aDGuv?p=preview

**Comment by hakib** [comment]
Hey @elifio, 
This is the problem we discussed above - How to properly position an element on a fixed container. 

I'm a bit time constrained at the moment so if anyone wants to take a crack at this i would appreciate it.

Haki.

**Comment by PSDCoder** [comment]
Hi pals! I think we shouldn't calculate position of dropdown dynamically. 
I forked mentioned above plunker and added styles which fix that problem: http://plnkr.co/edit/3rfOkq4D46mzwB5FXo53?p=preview

```css
/* fix styles */
[mass-autocomplete] {
  position: relative;
}

.ac-container {
  position: absolute;
  top: 100% !important;
  left: 0 !important;
  width: 100% !important;
}
```

What do you think about that?
